<?php

namespace Suivi\SuiviBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
    public function getNb() {

        return $this->createQueryBuilder('l')

            ->select('COUNT(l)')

            ->getQuery()

            ->getSingleScalarResult();

    }

}
