<?php

namespace Suivi\SuiviBundle\Entity;

/**
 * ContratsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratsRepository extends \Doctrine\ORM\EntityRepository
{
}
