<?php

namespace Suivi\SuiviBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Suivi\SuiviBundle\Entity\Categorie;

/**
 * OffresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffresRepository extends EntityRepository
{
    public function getOffreWithCategories($categoryNames)
    {
        $qb = $this->createQueryBuilder('a');
        $qb ->join('a.categ', 'c')
            ->addSelect('c');
        $qb->where($qb->expr()->in('c.nom', $categoryNames));

        return $qb->getQuery()
            ;
    }
   
    
    public function getNbOffres() {

        return $this->createQueryBuilder('l')

            ->select('COUNT(l)')

            ->getQuery()

            ->getSingleScalarResult();

    }
    
     public function getOffresbyStatus() {
         
         return $this->createQueryBuilder('l')
                ->where('l.status = 1')
                ->getQuery()
                 ->setFirstResult(0)
                 ->setMaxResults(5)
                ->getResult();
      
    }
}
