<?php

namespace Suivi\SuiviBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VentesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentesRepository extends EntityRepository
{
    public function getPropertiesEn() {
        return $this->createQueryBuilder('u')
            ->where('u.quantite = :quantite')
            ->setParameter('quantite', '5888')
            ->orderBy('u.quantite', 'ASC')
            ;
    }
    public function getrecette() {

        return $this->createQueryBuilder('l')

            ->select('SUM(l.quantite*c.prixunitaire)')
            ->join('l.offres', 'c')
            ->getQuery()

            ->getSingleScalarResult();

    }
     public function getSum() {

        return $this->createQueryBuilder('l')

            ->select('SUM(l.quantite)')
            ->groupBy('l.date')
            ->getQuery()

            ->getResult();

    }
   
}
